### ISSUE TITLE
Git.pp causes puppetmaster deployment to fail

### ISSUE THREAD

**Issue by stevechambers** [LandRegistry-Ops/puppet-control#37]
Git is a dependency of r10k and is therefore already declared as a package resource in the puppet-master configuration. Therefore puppet agent runs on the puppet-master will fail with a 'Duplicate declaration' error (as both git.pp and the r10k module are trying to install it). We therefore need to find an alternate way of applying git.pp only to the nodes that require it (i.e. not in the common.yaml file). 

I guess that there is also a strong possibility that the same issue will occur for gitlab-master

**Comment by benfairless** [comment]
Hmm... is this definitely the right place the error is occurring. Declaring a package twice shouldn't break anything unless they are asking  for different versions?

**Comment by stevechambers** [comment]
Fixed!
